/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as PetFoodsRouteImport } from './routes/pet-foods'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const PetFoodsRoute = PetFoodsRouteImport.update({
  id: '/pet-foods',
  path: '/pet-foods',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/b2b': typeof B2bRoute
  '/contact': typeof ContactRoute
  '/inquiry': typeof InquiryRoute
  '/pet-foods': typeof PetFoodsRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/b2b': typeof B2bRoute
  '/contact': typeof ContactRoute
  '/inquiry': typeof InquiryRoute
  '/pet-foods': typeof PetFoodsRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/b2b': typeof B2bRoute
  '/contact': typeof ContactRoute
  '/inquiry': typeof InquiryRoute
  '/pet-foods': typeof PetFoodsRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/b2b'
    | '/contact'
    | '/inquiry'
    | '/pet-foods'
    | '/private-label'
    | '/products'
    | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/b2b'
    | '/contact'
    | '/inquiry'
    | '/pet-foods'
    | '/private-label'
    | '/products'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/b2b'
    | '/contact'
    | '/inquiry'
    | '/pet-foods'
    | '/private-label'
    | '/products'
    | '/recipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  B2bRoute: typeof B2bRoute
  ContactRoute: typeof ContactRoute
  InquiryRoute: typeof InquiryRoute
  PetFoodsRoute: typeof PetFoodsRoute
  PrivateLabelRoute: typeof PrivateLabelRoute
  ProductsRoute: typeof ProductsRoute
  RecipesRoute: typeof RecipesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-foods': {
      id: '/pet-foods'
      path: '/pet-foods'
      fullPath: '/pet-foods'
      preLoaderRoute: typeof PetFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  B2bRoute: B2bRoute,
  ContactRoute: ContactRoute,
  InquiryRoute: InquiryRoute,
  PetFoodsRoute: PetFoodsRoute,
  PrivateLabelRoute: PrivateLabelRoute,
  ProductsRoute: ProductsRoute,
  RecipesRoute: RecipesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
