# Generated by Django 5.2.17 on 2026-08-21 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('VIP', 'VIP'), ('Standard', 'Standard'), ('Lead', 'Lead')], default='Lead', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('is_domestic', models.BooleanField(default=False)),
                ('payment_rail', models.CharField(blank=True, choices=[('razorpay', 'Razorpay (Domestic)'), ('advance_tt', 'Advance TT (International)'), ('lc_sight', 'LC at Sight (International)'), ('credit_terms', 'Approved Credit Terms')], max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('items_summary', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_status', models.CharField(choices=[('awaiting_quote', 'Awaiting Quote'), ('quoted', 'Quoted'), ('advance_paid', 'Advance Paid'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='awaiting_quote', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.customer')),
                ('source_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='enquiries.enquiry')),
                ('source_private_label_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='enquiries.privatelabelenquiry')),
            ],
        ),
    ]
