# Generated by Django 6.0.6 on 2026-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
