# Generated by Django 6.0.6 on 2026-08-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_email_drop_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('awaiting_quote', 'Awaiting Quote'), ('quoted', 'Quoted'), ('advance_paid', 'Advance Paid'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='awaiting_quote', max_length=20),
        ),
    ]
