# Generated by Django 6.0.6 on 2026-08-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
