# Generated by Django 5.2.17 on 2026-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_removal_status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_image_transparent',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_image_transparent',
            field=models.URLField(blank=True, default=''),
        ),
    ]
