import { useState } from 'react';
import { PawPrint, Minus, Plus, MessageCircle } from 'lucide-react';
import { buildWhatsAppLink } from '@/lib/whatsapp';

function LightPetCard({ product }) {
  const [hovered, setHovered] = useState(false);
  const [qty, setQty] = useState(1);
  const waLink = buildWhatsAppLink(`Pet Food: ${product.name}`, qty);
  return <div onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)} onClick={() => setHovered((value) => !value)} style={{ background: '#ffffff', borderRadius: 'var(--radius-xl)', border: `1.5px solid ${hovered ? product.accent : 'var(--border-light)'}`, overflow: 'hidden', boxShadow: hovered ? '0 20px 50px rgba(0,0,0,0.12)' : 'var(--shadow-sm)', display: 'flex', flexDirection: 'column', cursor: 'pointer' }}><div style={{ position: 'relative', aspectRatio: '4/5', overflow: 'hidden', background: 'var(--light-grey)' }}><img src={product.packImage} alt={product.name} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: hovered ? 0 : 1, transition: 'all 0.5s ease' }} /><img src={product.ingredientImage} alt="" aria-hidden style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: hovered ? 1 : 0, transition: 'all 0.5s ease' }} /><span style={{ position: 'absolute', top: 12, left: 12, zIndex: 5, display: 'inline-flex', alignItems: 'center', gap: 4, padding: '4px 10px', borderRadius: 9999, background: 'rgba(217,123,61,0.9)', color: 'white', fontSize: 10, fontWeight: 700, textTransform: 'uppercase' }}><PawPrint size={11} /> For Pets</span><div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '20px 16px 16px', background: 'linear-gradient(to top, rgba(255,255,255,0.95), transparent)', opacity: hovered ? 1 : 0, transition: 'all 0.3s ease', zIndex: 10 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><strong>Select Quantity:</strong><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><button onClick={(event) => { event.stopPropagation(); setQty((value) => Math.max(1, value - 1)); }}><Minus size={13} /></button><span>{qty}</span><button onClick={(event) => { event.stopPropagation(); setQty((value) => Math.min(20, value + 1)); }}><Plus size={13} /></button></div></div><a href={waLink} target="_blank" rel="noopener noreferrer" onClick={(event) => event.stopPropagation()} className="btn btn-whatsapp" style={{ marginTop: 10, padding: 10, justifyContent: 'center' }}><MessageCircle size={14} /> Inquire on WhatsApp</a></div></div><div style={{ padding: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><span style={{ color: product.accent, fontWeight: 800, fontSize: 10, textTransform: 'uppercase' }}>{product.category}</span><span style={{ color: 'var(--text-dark)', fontWeight: 800 }}>{product.price}</span></div><h3 style={{ color: 'var(--text-dark)', fontWeight: 800, fontSize: 17 }}>{product.name}</h3><p style={{ color: 'var(--text-body)', fontSize: 13, lineHeight: 1.5 }}>{product.blurb}</p></div></div>;
}

export default function PetFoods({ products = [], isLoading = false, error = null }) {
  if (isLoading) return <section style={{ padding: '64px 0', background: 'white' }}><div className="container"><p>Loading pet foods...</p></div></section>;
  if (error) return <section style={{ padding: '64px 0', background: 'white' }}><div className="container"><p style={{ color: 'var(--red)' }}>{error}</p></div></section>;
  const petFoods = products.filter((product) => product.category.toLowerCase() === 'pet food');
  return <section style={{ padding: '64px 0', background: 'white' }}><div className="container"><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 24 }}>{petFoods.map((product) => <LightPetCard key={product.id} product={product} />)}</div>{petFoods.length === 0 && <p style={{ padding: '64px 0', textAlign: 'center' }}>No pet foods available right now.</p>}</div></section>;
}
