# Generated by Django 5.2.17 on 2026-08-21 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enquiry_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('buyer_type', models.CharField(blank=True, choices=[('importer', 'Importer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('food_manufacturer', 'Food Manufacturer'), ('retailer', 'Retailer'), ('horeca', 'HoReCa'), ('restaurant', 'Restaurant / Food Service'), ('private_label_brand', 'Private Label Brand'), ('pet_food_manufacturer', 'Pet Food Manufacturer'), ('ingredient_trader', 'Ingredient Trader'), ('ecommerce', 'E-commerce'), ('other', 'Other')], max_length=30)),
                ('interested_products', models.JSONField(default=list)),
                ('quantity_requirement', models.CharField(max_length=100)),
                ('private_label_required', models.BooleanField(default=False)),
                ('packaging_preference', models.CharField(blank=True, max_length=100)),
                ('target_market', models.CharField(blank=True, max_length=100)),
                ('additional_requirements', models.TextField(blank=True)),
                ('shipping_method', models.CharField(blank=True, choices=[('sea_fcl', 'Sea FCL'), ('sea_lcl', 'Sea LCL'), ('air', 'Air Freight'), ('courier', 'Courier / Express'), ('buyer_arranged', 'Buyer-arranged logistics')], max_length=20)),
                ('delivery_timeline', models.CharField(blank=True, max_length=100)),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DDP', 'DDP')], max_length=10)),
                ('payment_terms', models.CharField(blank=True, choices=[('advance_tt', 'Advance TT'), ('lc_sight', 'LC at Sight'), ('partial_advance', 'Partial Advance + Balance'), ('credit_terms', 'Credit Terms (subject to approval)')], max_length=20)),
                ('packaging_reference_file', models.FileField(blank=True, null=True, upload_to='enquiries/packaging_refs/')),
                ('brand_guidelines_file', models.FileField(blank=True, null=True, upload_to='enquiries/brand_guidelines/')),
                ('po_file', models.FileField(blank=True, null=True, upload_to='enquiries/purchase_orders/')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Pending', 'Pending'), ('Closed', 'Closed')], db_index=True, default='New', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLabelEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enquiry_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('step_completed', models.PositiveIntegerField(default=1)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('buyer_type', models.CharField(blank=True, choices=[('importer', 'Importer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('food_manufacturer', 'Food Manufacturer'), ('retailer', 'Retailer'), ('horeca', 'HoReCa'), ('restaurant', 'Restaurant / Food Service'), ('private_label_brand', 'Private Label Brand'), ('pet_food_manufacturer', 'Pet Food Manufacturer'), ('ingredient_trader', 'Ingredient Trader'), ('ecommerce', 'E-commerce'), ('other', 'Other')], max_length=30)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('brand_status', models.CharField(blank=True, choices=[('existing', 'Existing Brand'), ('new', 'New Brand')], max_length=10)),
                ('brand_website_social', models.CharField(blank=True, max_length=255)),
                ('target_market', models.CharField(blank=True, max_length=100)),
                ('desired_specification', models.TextField(blank=True)),
                ('cut_size_form', models.CharField(blank=True, max_length=255)),
                ('flavour_recipe', models.CharField(blank=True, max_length=255)),
                ('packaging_format', models.CharField(blank=True, choices=[('retail_pouch', 'Retail Pouch'), ('glass_jar', 'Glass Jar/Bottle'), ('bulk_bag', 'Bulk Bag'), ('sachet', 'Sachet'), ('custom', 'Custom Packaging')], max_length=20)),
                ('quantity_range', models.CharField(blank=True, choices=[('trial', 'Trial Order'), ('100_500', '100–500 units'), ('500_1000', '500–1,000 units'), ('1000_5000', '1,000–5,000 units'), ('5000_10000', '5,000–10,000 units'), ('10000_plus', '10,000+ units'), ('bulk_mt', 'Bulk / MT requirement')], max_length=20)),
                ('has_existing_artwork', models.BooleanField(default=False)),
                ('needs_design_support', models.BooleanField(default=False)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='private_label/logos/')),
                ('brand_guidelines_file', models.FileField(blank=True, null=True, upload_to='private_label/guidelines/')),
                ('packaging_reference_file', models.FileField(blank=True, null=True, upload_to='private_label/packaging_refs/')),
                ('custom_label_requirements', models.TextField(blank=True)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('intended_application', models.CharField(blank=True, max_length=255)),
                ('required_certifications', models.JSONField(default=list)),
                ('import_requirements', models.TextField(blank=True)),
                ('existing_regulatory_specs', models.TextField(blank=True)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('target_price_range', models.CharField(blank=True, max_length=100)),
                ('desired_incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DDP', 'DDP')], max_length=10)),
                ('preferred_payment_terms', models.CharField(blank=True, choices=[('advance_tt', 'Advance TT'), ('lc_sight', 'LC at Sight'), ('partial_advance', 'Partial Advance + Balance'), ('credit_terms', 'Credit Terms (subject to approval)')], max_length=20)),
                ('shipping_destination', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
    ]
