# Generated by Django 5.2.17 on 2026-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='transparent_file_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
