# Generated by Django 5.2.17 on 2026-08-21 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('obtained', 'Obtained'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='planned', max_length=15)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('badge_icon_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('product', 'Product'), ('private_label', 'Private Label'), ('shipping', 'Shipping & Trade'), ('quality', 'Quality & Certification')], default='general', max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='FounderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(default='Founder & Executive Director', max_length=150)),
                ('message', models.TextField()),
                ('photo_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssuranceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='ShieldCheck', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RegionComplianceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(max_length=10, unique=True)),
                ('region_name', models.CharField(max_length=100)),
                ('required_fields', models.JSONField(default=list)),
                ('relevant_certifications', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Bharat Freeze Dry Foods (BFF)', max_length=255)),
                ('tagline', models.CharField(default='Sourcing the Best Quality, For You.', max_length=255)),
                ('company_address', models.TextField(default='Gujarat, India')),
                ('support_email', models.EmailField(default='export@bff-foods.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=50)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('social_links', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('route_url', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('content_payload', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
